### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BelaBartok39**
A comma isn't usually needed after a conjunction. If a pause is what you mean, perhaps three dots would be more appropriate. The other option would be for it to just read "And it's fast!"

# Type of PR (feature, enhancement, bug fix, etc.)

## Description

Please include a summary of the change and which issue is fixed.

Fixes # (issue)

## Why should this be added

Explain value.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] Checks (StandardRB & Prettier-Standard) are passing
- [ ] This is not a documentation update

Please note that the best way to suggest changes or updates to the [documentation](https://docs.stimulusreflex.com) is to [join Discord](https://discord.gg/stimulus-reflex) and leave a note in the #docs channel. Any documentation updates posted as PRs cannot be accepted at this time. :heart:

### CODE REVIEW

**Comment by leastbad** [comment]
> Please note that the best way to suggest changes or updates to the [documentation](https://docs.stimulusreflex.com/) is to [join Discord](https://discord.gg/stimulus-reflex) and leave a note in the #docs channel. Any documentation updates posted as PRs cannot be accepted at this time. ❤️

**Comment by BelaBartok39** [comment]
Leastbad! Roger roger :)

**Comment by leastbad** [comment]
FWIW, I've put the change on the list! I just can't merge documentation PRs because it just breaks everything, as it explains in the PR template.

**Comment by BelaBartok39** [comment]
I missed it :( I did read the CoC and checklist though. I hope to help in some tiny way! Anyways, we need to have a rails marathon again soon. Hahaha, lord knows I have some questions. I'll message you on discord so we are not having a PR comment convo.

**Pull request closed without merging**
