### PR TITLE
Provide proxy methods truthy? and numeric on Element

### PR DESCRIPTION
**Pull request by julianrubisch**
# Feature

## Description

This PR introduces two proxy methods:

- `truthy?`,
- `numeric`

on `StimulusReflex` that work the same way as `signed/unsigned`: They try to coerce a dataset attribute into boolean or numeric given to it in hash notation:

```ruby
element.truthy?[:prevent_save]
element.numeric[:price]
```

## Why should this be added

Easier access to parsed/cast boolean and numeric values in the element's dataset

## Checklist

- [X] My code follows the style guidelines of this project
- [X] Checks (StandardRB & Prettier-Standard) are passing
- [X] This is not a documentation update

Please note that the best way to suggest changes or updates to the [documentation](https://docs.stimulusreflex.com) is to [join Discord](https://discord.gg/stimulus-reflex) and leave a note in the #docs channel. Any documentation updates posted as PRs cannot be accepted at this time. :heart:

### CODE REVIEW

**Review by leastbad — COMMENTED** [review]
I'm generally positive about these additions.

The only question I have is about the practical and meaningful difference between `1` and `1.0`. Since Ruby does a pretty good job of coercing floats into integers, perhaps there's nothing more to say and float is a reasonable default.

After all, if someone truly needs an integer, they certainly have the power to make that happen.

**Review by marcoroth — COMMENTED** [review]
I think it would also make sense to provide a `#falsy?` accessor, or does something speak against that?

I'm also not too sure about the general `#numeric` accessor. Wouldn't it make more sense to provide one for integer values and one for float values?

**Comment by julianrubisch** [comment]
Personally I think falling back to float is just ok.

About falsey, I don't know... I mean there's nothing wrong here but is there additional value?

**Comment by hopsoft** [comment]
I like this but recommend a few changes, some minor renaming and I'd like to have the abstraction available to `dataset` also for consistent API coverage.

I'm thinking of an API more like this.

```ruby
element.boolean[:prevent_save]
element.numeric[:price]
element.dataset.boolean[:prevent_save]
element.dataset.numeric[:price]
``` 

Thoughts?

**Comment by julianrubisch** [comment]
Okay with me. I remember we went back and forth regarding "truthy" and settled with it for some reason 🤔

**Comment by julianrubisch** [comment]
I think the rationale was

1. naming collisions (`boolean`)
2. blank data attributes that don't explicitly have a value of `"true"`, like `checked`

And as for consistency I'm unsure ... do we actually have methods for `signed` etc on the dataset?

**Comment by leastbad** [comment]
> And as for consistency I'm unsure ... do we actually have methods for `signed` etc on the dataset?

https://github.com/stimulusreflex/stimulus_reflex/blob/db9dc1df62a1ded9a37287f1f963583d247e4dcf/lib/stimulus_reflex/element.rb#L20

**Comment by julianrubisch** [comment]
Sorry, on `element.dataset`, as @hopsoft suggested above

**Comment by hopsoft** [comment]
I propose creating `class Dataset` as a first class citizen, then moving the `signed` and the typed value accessor implementations into `Dataset`, then have `Element` delegate to the `Dataset` methods.

**Pull request merged**
