### PR TITLE
Add localization example to ApplicationReflex template

### PR DESCRIPTION
**Pull request by erlingur**
# Type of PR (feature, enhancement, bug fix, etc.)

Enhancement

## Description

Needed to add full localization to all reflexes at the same time. This is an easier way than the current docs suggest, which is to create a helper method `with_locale` and wrap it around any code that needs it.

## Why should this be added

This would be helpful for anyone that needs to maintain an app that has multiple languages.

## Other

Feel free to suggest a change to the wording, English is my second language. I also went with the `before_reflex :name, def name` code style instead of `before_reflex do CODE end` style since I prefer that for my own code but you can change it if you wish.

### CODE REVIEW

**Comment by leastbad** [comment]
This might be a stupid question (and I am being being lazy by not just testing it) but what happens if someone uncomments the `before_reflex` in ApplicationReflex and also declares a `before_reflex` in their Reflex class?

**Comment by erlingur** [comment]
They would have two `before_reflex` callbacks. I do that in my apps. You can have multiple `before_reflex`s at the same time. I'm assuming `before_reflex` works the same as `before_action`.

**Comment by leastbad** [comment]
I trust you! I just would have expected that a developer would have to call `super` to have them both fire.

**Comment by erlingur** [comment]
Oh no worries. I'm not in front of my computer so I can't test it but I'm basing this on how `before_action` works. Now I want to test it to make sure :)

**Comment by leastbad** [comment]
You are 100% correct. You can have multiple `before_reflex` calls. I'm not sure how I didn't consciously realize that until just now.

**Comment by erlingur** [comment]
Good to know, thanks! :)

**Pull request merged**
